import '../styles/globals.css'
import './head'

export const metadata = {
  title: 'Experteam AI',
  description: 'Generated by Next.js',
  keywords: ['Experteam', 'AI', 'Writer'],
  icons: {
    icon: '/favicon.ico',

  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head/>
      <body>{children}</body>
    </html>
  )
}
